apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: octobay-app
  name: octobay-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octobay-app
  strategy: {}
  template:
    metadata:
      labels:
        app: octobay-app
    spec:
      containers:
      - image: octobay/app
        name: app