name: OctoBay app - Test, Build, Push, Deploy

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Build Docker image
      env:
        TAG: ${{ steps.date.outputs.date }}
      run: docker build -t octobay/app:$TAG .
    - name: Authenticate with Docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push Docker image
      env:
        TAG: ${{ steps.date.outputs.date }}
      run: docker push octobay/app:$TAG
  
  deploy:
    name: Deploy to Kubernetes
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
    - name: Use context
      run: kubectl config use-context octobay-api
    - name: Deploy to K8s
      run: kubectl apply -f .k8s/